import type { PortfolioData } from "./types"

export const initialPortfolioData: PortfolioData = {
  about: {
    name: "Alex Rivera",
    title: "Full-Stack Engineer & Creative Developer",
    bio: "I craft exceptional digital experiences through code, design, and innovation. Specializing in modern web technologies with a passion for building products that make a difference.",
    location: "San Francisco, CA",
    email: "alex@example.com",
    profileImage: "/placeholder-user.jpg",
    github: "alexrivera",
    linkedin: "alexrivera",
    twitter: "alexrivera",
  },
  projects: [
    {
      id: "1",
      title: "Neural Canvas",
      description: "AI-powered design tool that transforms ideas into visual masterpieces",
      longDescription:
        "Built with Next.js, TensorFlow.js, and WebGL. Features real-time AI generation, collaborative editing, and export to multiple formats.",
      image: "/ai-design-tool-interface-dark-modern.jpg",
      tags: ["Next.js", "AI/ML", "WebGL", "TypeScript"],
      liveUrl: "https://neuralcanvas.com",
      githubUrl: "https://github.com/example/neural-canvas",
      featured: true,
      year: "2024",
    },
    {
      id: "2",
      title: "Quantum Dashboard",
      description: "Real-time analytics platform for modern SaaS applications",
      longDescription:
        "Enterprise-grade dashboard with live data visualization, custom reports, and predictive analytics. Handles millions of events per second.",
      image: "/analytics-dashboard-charts-graphs-modern.jpg",
      tags: ["React", "D3.js", "WebSocket", "Node.js"],
      liveUrl: "https://quantum-dashboard.com",
      featured: true,
      year: "2024",
    },
    {
      id: "3",
      title: "CodeFlow Studio",
      description: "Collaborative code editor with AI pair programming",
      longDescription: "VSCode-inspired web IDE with real-time collaboration, AI suggestions, and integrated terminal.",
      image: "/code-editor-dark-theme-programming.jpg",
      tags: ["Monaco Editor", "WebRTC", "AI", "TypeScript"],
      githubUrl: "https://github.com/example/codeflow",
      featured: true,
      year: "2023",
    },
    {
      id: "4",
      title: "Harmony Social",
      description: "Privacy-first social platform for creative communities",
      longDescription: "End-to-end encrypted messaging, content sharing, and community management tools.",
      image: "/social-media-app-modern-interface.jpg",
      tags: ["Next.js", "Supabase", "E2E Encryption"],
      featured: false,
      year: "2023",
    },
    {
      id: "5",
      title: "Motion Metrics",
      description: "Fitness tracking app with computer vision",
      longDescription: "Uses device camera to track exercises, count reps, and provide form feedback using ML models.",
      image: "/fitness-app-tracking-modern-ui.jpg",
      tags: ["React Native", "TensorFlow", "Computer Vision"],
      liveUrl: "https://motionmetrics.app",
      featured: false,
      year: "2023",
    },
    {
      id: "6",
      title: "Echo Finance",
      description: "Personal finance manager with smart insights",
      longDescription: "Automated expense tracking, budget planning, and AI-powered financial recommendations.",
      image: "/finance-app-charts-modern-interface.jpg",
      tags: ["Next.js", "Prisma", "AI", "Charts"],
      featured: false,
      year: "2022",
    },
  ],
  skills: [
    { id: "1", name: "React", category: "frontend", level: 95, icon: "code" },
    { id: "2", name: "Next.js", category: "frontend", level: 95, icon: "globe" },
    { id: "3", name: "TypeScript", category: "frontend", level: 90, icon: "braces" },
    { id: "4", name: "Tailwind CSS", category: "frontend", level: 90, icon: "palette" },
    { id: "5", name: "Node.js", category: "backend", level: 85, icon: "server" },
    { id: "6", name: "PostgreSQL", category: "backend", level: 80, icon: "database" },
    { id: "7", name: "GraphQL", category: "backend", level: 75, icon: "workflow" },
    { id: "8", name: "Python", category: "backend", level: 70, icon: "terminal" },
    { id: "9", name: "Git", category: "tools", level: 90, icon: "git" },
    { id: "10", name: "Docker", category: "tools", level: 75, icon: "container" },
    { id: "11", name: "AWS", category: "tools", level: 70, icon: "cloud" },
    { id: "12", name: "Figma", category: "design", level: 85, icon: "figma" },
  ],
  skillCategories: [
    {
      id: "1",
      key: "frontend",
      title: "Frontend Development",
      description: "Building responsive, accessible, and performant user interfaces with modern frameworks and tools.",
      icon: "layers",
      skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "HTML/CSS"],
    },
    {
      id: "2",
      key: "backend",
      title: "Backend Development",
      description: "Designing scalable APIs, microservices, and database architectures for robust applications.",
      icon: "server",
      skills: ["Node.js", "PostgreSQL", "GraphQL", "Python", "REST APIs"],
    },
    {
      id: "3",
      key: "tools",
      title: "DevOps & Tools",
      description: "Streamlining development workflows with CI/CD, containerization, and cloud infrastructure.",
      icon: "container",
      skills: ["Git", "Docker", "AWS", "CI/CD", "Linux"],
    },
    {
      id: "4",
      key: "design",
      title: "Design & UI/UX",
      description: "Creating intuitive user experiences with modern design tools and principles.",
      icon: "palette",
      skills: ["Figma", "UI Design", "Prototyping", "Design Systems"],
    },
  ],
  services: [
    {
      id: "1",
      title: "AI / Machine Learning Solutions",
      description: "Custom ML & deep learning models, predictive systems, optimization, and real-world AI deployments.",
      icon: "brain",
      tags: ["TensorFlow", "PyTorch", "Scikit-learn", "MLOps"],
    },
    {
      id: "2",
      title: "NLP & Generative AI",
      description: "LLM-based chatbots, RAG systems, voice/text AI, prompt engineering, and fine-tuned models.",
      icon: "message-square-text",
      tags: ["OpenAI", "LangChain", "RAG", "Fine-tuning"],
    },
    {
      id: "3",
      title: "Agentic AI & Automation",
      description: "Autonomous AI agents, workflow automation using n8n & MCP, business process optimization.",
      icon: "bot",
      tags: ["n8n", "MCP", "AutoGPT", "Workflows"],
    },
    {
      id: "4",
      title: "Full-Stack Web Development",
      description: "Scalable web apps, AI-powered dashboards, APIs, and production-ready systems.",
      icon: "globe",
      tags: ["React", "Next.js", "Node.js", "MongoDB"],
    },
    {
      id: "5",
      title: "Mobile App Development",
      description: "Cross-platform mobile apps with AI integration using Flutter or React Native.",
      icon: "smartphone",
      tags: ["Flutter", "React Native", "iOS", "Android"],
    },
    {
      id: "6",
      title: "Data Analysis & Insights",
      description: "Data preprocessing, visualization, ML insights, and decision-driven analytics.",
      icon: "bar-chart-3",
      tags: ["Python", "Pandas", "Power BI", "SQL"],
    },
  ],
  experience: [
    {
      id: "1",
      company: "Tech Innovations Inc",
      role: "Senior Full-Stack Engineer",
      period: "2022 - Present",
      description: "Leading development of next-generation SaaS products",
      achievements: [
        "Architected and launched 3 major product features serving 50K+ users",
        "Reduced application load time by 60% through optimization",
        "Mentored 5 junior engineers and established code review standards",
      ],
      current: true,
    },
    {
      id: "2",
      company: "Creative Labs",
      role: "Full-Stack Developer",
      period: "2020 - 2022",
      description: "Built innovative web applications for startups and enterprises",
      achievements: [
        "Developed 10+ production applications using modern stack",
        "Implemented CI/CD pipelines reducing deployment time by 70%",
        "Collaborated with design team on award-winning user interfaces",
      ],
      current: false,
    },
    {
      id: "3",
      company: "Digital Solutions",
      role: "Frontend Developer",
      period: "2019 - 2020",
      description: "Crafted responsive and accessible web interfaces",
      achievements: [
        "Built component library used across 15+ projects",
        "Achieved 100% accessibility score on all deliverables",
        "Reduced bundle size by 40% through code splitting",
      ],
      current: false,
    },
  ],
}
